GET https://kn0fw7bjpk.execute-api.eu-west-1.amazonaws.com/dev/public/
###

GET https://kn0fw7bjpk.execute-api.eu-west-1.amazonaws.com/dev/private/
Authorization: eyJraWQiOiJKNndHNkFHOUlVbXh5NExXT2ZjRlFjTXV3YVwvcVd4YkFmYlNtMDVnR0g5Yz0iLCJhbGciOiJSUzI1NiJ9.eyJvcmlnaW5fanRpIjoiNGRiZWMwNjMtNzI5NS00NzNmLTgxOWUtZTRmMzA0OWNmOGZiIiwic3ViIjoiNzI5NWY0YTQtNzA2MS03MDgwLTU3MGItMzlmYmM4N2NjYTA3IiwiYXVkIjoiMWh1M2ZidGprNml0cXIza2dnM3Mwa3FydG4iLCJldmVudF9pZCI6IjYxZTg0N2YxLTgyMDYtNDZlMi05NmE2LTY1MTIzMmRmNWUxZCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzM1NjUyMzgyLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9pMWw1SDlGU08iLCJjb2duaXRvOnVzZXJuYW1lIjoiYmFyb3NhbnUiLCJleHAiOjE3MzU2NTU5ODIsImlhdCI6MTczNTY1MjM4MiwianRpIjoiZTA1YjNjYmMtY2YyNC00NGU0LWI4NmUtMWI2MjczNzBlMzAyIn0.IUlWm291sdqrvW1E1Pm6rZLWMMt3zjQhmwGEYttXDsa2BAPOxIwcyyrYo8hgUOcotDFPM1wr8W1gjs_19tIQT7q9Y3XNru1DrtJQmYZ3-7vgVWs4D2ufXVoDb9EXEeZy7bsQvzbr2HCsNNpBzeUGDyn9Sgux7LrqS2qzBG3nN4S_3dStRcWSEYY_3T72CI8JbDdEXtX8DX-4_TNiCpVBhVIadFk3yGU55cX41pI11xXWhr-86Ba9wU-1UF3U5YQbSOt01fNtwk7_e0xuwlPZOQiFP5FDpwdU4V3lJExpT01UF2ilpZkItK4NGoNGsnY4CI68fesUF3Fsw0fqZdZRgg
###